CREATE TABLE IF NOT EXISTS responses (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);